### ISSUE TITLE
Unable to run the application due to null safety issue

### ISSUE THREAD

**Issue by allamrajukrish** [SatYu26/Portfolio#1]
Hi Satya, I'm using flutter 2 stable version and when I try to run the app I'm getting below error. 
_```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:                                              
                                                                        
 - package:steps                                                        
 - package:flutter_icons                                                
                                                                        
For solutions, see https://dart.dev/go/unsound-null-safety              
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-2.3.1-nullsafety.0/lib/src/extensions/context_ext.dart:177:36: Error: No named
parameter with the name 'nullOk'.
      Actions.invoke(this, intent, nullOk: nullOk) as bool?;            
                                   ^^^^^^                               
../../../../development/flutter/packages/flutter/lib/src/widgets/actions.dart:898:18: Context: Found this candidate, but the arguments don't match.
  static Object? invoke<T extends Intent>(                              
                 ^^^^^^                                                 
Unhandled exception:                                                    
Bad state: Unsupported Null Safety mode NonNullableByDefaultCompiledMode.Invalid, in null.
#0      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:435:9)
#1      JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:144:33)
#2      FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:632:20)
<asynchronous suspension>                                               
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:545:9)
<asynchronous suspension>                                               
#4      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1105:11)
<asynchronous suspension>                                               
the Dart compiler exited unexpectedly.                                  
Waiting for connection from debug service on Chrome...             16.0s
Failed to compile application.
```_

**Comment by SatYu26** [comment]
please try running by using this flag `--no-sound-null-safety`
